_scriptHandle = ["record.startRecordAsync"] spawn DBMU_fnc_createAsync;
waitUntil { scriptDone _scriptHandle && DBMU_is_radio_on == false };
_scriptHandle = ["record.stopRecordAsync"] spawn DBMU_fnc_createAsync;
waitUntil { scriptDone _scriptHandle };
_scriptHandle = ["record.transcribe_audioAsync"] spawn DBMU_fnc_createAsync;
waitUntil { scriptDone _scriptHandle };
_scriptHandle = ["record.chat_with_gptAsync"] spawn DBMU_fnc_createAsync;
waitUntil { scriptDone _scriptHandle };
[] call DBMU_fnc_playBeep;
[] spawn DBMU_fnc_backgroundHelicopter;
diag_log "0 text_to_speechAsync";
_scriptHandle = ["record.text_to_speechAsync"] spawn DBMU_fnc_createAsync;
diag_log "speech to text waituntil";
waitUntil { scriptDone _scriptHandle };
diag_log "speech to text complete";
diag_log format ["1 DBMU_is_fak_responding%1", DBMU_is_fak_responding];
DBMU_is_fak_responding = true;
diag_log format ["2 DBMU_is_fak_responding%1", DBMU_is_fak_responding];
diag_log "3 speech to text complete";
[] call DBMU_fnc_playBeep;